### PR TITLE
Skip vpc_SecureHash and vpc_SecureHashType params in SHA256 Hash Calculation

### LINKED ISSUE #6: Switch from MD5 to SHA256 has broken hash validation
The new release v2.2 with SHA256 hash validation has broken 3 party purchases with our MIGS gateway. Reverting to MD5 version (2.1.1) works. I'm unable to find any documentation from our bank on SHA256 support nor how to verify the hash.

### PR DESCRIPTION
**Pull request by lucasnetau**
This fixes thephpleague/omnipay-migs#6

### CODE REVIEW

**Comment by delatbabel** [comment]
Merged, thanks for this.

Can you please test this in production and then confirm that it works. Then I will tag for release.

**Comment by lucasnetau** [comment]
Hi, we have been running this in production and have confirmed successful payments against both production and test MIGS accounts.

**Comment by lucasnetau** [comment]
Hi @delatbabel, Will a new release go out soon?

**Comment by delatbabel** [comment]
Released as v2.2.1

**Comment by alauddinmondal** [comment]
is there any wordpress plugin developer for migs? please help me my mail id lincolnuniversitydxb@gmail.com

**Pull request merged**
