### PR TITLE
- Complete the ThreePartyRefundRequest

### PR DESCRIPTION
**Pull request by igorkosteski**
- Complete the ThreePartyRefundRequest 
- Bug Fix Response getCode
- Update the UnitTest:

### CODE REVIEW

**Comment by delatbabel** [comment]
This PR does not meet coding standards and so CodeSniffer is failing it (use spaces for indenting not tabs).

**Comment by igorkosteski** [comment]
@delatbabel,
I committed the code standard fixes and CodeSniffer and tests are passing now. 
https://travis-ci.org/thephpleague/omnipay-migs/builds/233298267
http://prntscr.com/f95iee
Can you see the error form hhvm:
https://travis-ci.org/thephpleague/omnipay-migs/jobs/233298273 
http://prntscr.com/f95kma

**Comment by delatbabel** [comment]
Hi, thanks for the fixes. Yes we're aware of the hhvm issue on travis.  It's not considered important but if you're submitting any more PRs then just remove the "hhvm" line from .travis.yml and that will make the problem go away.

Thanks for the contribution.  I will merge this now, please ensure that this works in production (breaks no existing code) and then I will tag for release.

**Comment by igorkosteski** [comment]
@delatbabel,
I tested the I confirm you that working fine.
Can you make an release with the new code?

**Comment by delatbabel** [comment]
Released as v2.2.2

**Pull request merged**
