### PR TITLE
upgrade to omnipay/common:v3

### PR DESCRIPTION
**Pull request by jsgv**
I started to make updates for omnipay/common ^3.

There is one error I was getting, but I am unsure about how to fix. Let me know what else I can do, or what I am missing. Just trying to update this package to use the latest omnipay/common lib.

Thanks

omnipay-migs

### CODE REVIEW

**Comment by barryvdh** [comment]
Can you update the travis matrix?
What is in the response? Perhaps you need to cast the body to string (or use getBody()->getContents())

**Comment by jsgv** [comment]
@barryvdh Made additional updates.

**Comment by barryvdh** [comment]
Looks good, can you just drop the 5.4, 5.5 and hhvm builds from travis?

**Comment by barryvdh** [comment]
Never mind, did that myself. Hopefully should be good now.

**Comment by jsgv** [comment]
@barryvdh Thanks!

**Pull request merged**
